### ISSUE TITLE
Pytanie do pd2

### ISSUE THREAD

**Issue by hbaniecki** [mini-pw/2020Z-ProgramowanieWR#104]
"Przygotuj funkcję, która jako argument przyjmuje dowolną funkcję i zwraca funkcję, która wykonuje dokładnie to samo, tylko w NSE."
W przykładzie funkcja `min_NSE` nie wykonuje dokładnie tego samego co `min`. Nie możemy wykonać:
```
x <- list(a = c(1, 2, 30), b = c(2, 1))
min(x, "a")
```
Rozumiem jednak w jaki sposób ma to działać dla podanych w opisie funkcji `min`, `mean` i `unlist`.
Nie rozumiem w jaki sposób ma to działać dla funkcji `lm`.
```
new_lm <- zadanieDomowe(lm)
new_lm(iris, Sepal.Length~Sepal.Width)
# czy
new_lm(iris, Sepal.Length, Sepal.Width)
```
Czy to oznacza, że w tym wypadku może być więcej niż jeden argument (x zamiast "x")? Są jeszcze inne możliwości? "dokładnie to samo, tylko w NSE" nie jest dla mnie do końca jasne.

**Comment by michbur** [comment]
```R
new_lm <- zadanieDomowe(lm)
new_lm(iris, formula = Sepal.Length~Sepal.Width)
new_lm(iris, formula = Sepal.Length~Sepal.Width - 1)
```

**Comment by hbaniecki** [comment]
`lm` działa tylko dla formuły, a nie działa dla argumentów `x` i `y`. To znaczy, że mamy to wyifować i sklejać `x` i `y` w formułę, czy to ostatnie wywołanie jednak nie powinno działać? (bo nowa funkcja ma robić dokładnie to samo, tylko w NSE)

**Comment by hbaniecki** [comment]
Ten ostatni przykład chyba nie powinien działać, bo lm działa tylko na formułach? Chyba, że mamy zrobić if(lm) i sklejać argumenty w formułę?

**Comment by michbur** [comment]
Mój błąd. Usunąłem wersję z x i y.

**Comment by piotr-ole** [comment]
Czym się różni new_lm od lm? Mogę wywołać:

``
lm(iris, formula = Sepal.Length~Sepal.Width)
``

i to działa tak samo.

**Comment by hbaniecki** [comment]
Niczym chyba. Chodzi o to żeby w takim przypadku też działało.

**Comment by piotr-ole** [comment]
Hmm, bo chyba dalej nie widzę jak ten przykład z lm łączy się z przykładem z min. W min wybieramy podlistę z listy, a tutaj wywołujemy zwyczajnie funkcję z argumentem, więc de facto co innego. Czy chodzi o to, żeby powiedzmy ta funkcja zadanieDomowe zwracała nam coś co niejako zadziała w jednym z dwóch przypadków? Np. spóbuje wziąć podlistę, a jak się nie uda to wywoła funkcję z argumentem.
