### ISSUE TITLE
Project 2 - Quickchartr - getElementNSE

### ISSUE THREAD

**Issue by JanSawicki** [mini-pw/2020Z-ProgramowanieWR#225]
@michbur 
Could you explain once again why the function [getElementNse](https://github.com/LuPaRaMySa/quickchartR/blob/607edf15494222977ab059d72faf176cc96c4397/R/quickchartR.R#L133) in Quickchartr code is useless? 
I cannot imagine how the code may work without it.

**Comment by michbur** [comment]
@JanSawicki if you are using substitute as here https://github.com/LuPaRaMySa/quickchartR/blob/1d275fc2e97e5ad93344f1017fa56e566b4c9bd0/R/quickchartR.R#L217 you could directly go to the Extract ([).

**Comment by JanSawicki** [comment]
> go to the Extract ([)
What is "Extract"?

**Comment by JanSawicki** [comment]
Thank you!

For those looking for the solution, please take a look at:
https://github.com/LuPaRaMySa/quickchartR/commit/46c0d2ccff45fda01415c4e84f6ff7268bcc704f
or
https://github.com/LuPaRaMySa/quickchartR/blob/241a66edc5c5c003b8359f817be5f747b8077018/R/quickchartR.R#L198
